# Docker compose
#   Zabbix MySQL/PostgreSQL, Nginx, Agent, Trapper
#--------------------------------------------------------------------
# For setup:
#   > docker compose [--profile <prof_type>] [--profile <prof_type>] up -d
#    Or
#   > COMPOSE_PROFILES=<prof_type>[,<prof_type>] docker compose up
#    where <prof_type>:
#     all-64 -> select all for DB type mysql and version 6.4
#     agent-64 -> select agent and trapper version 6.4
#     mysql-64 | pgsql-64 -> only zabbix server, nginx and DB for zabbix-6.4-latest (default)
#
# Example: 
#   For full setup zabbix-mysql 6.4:
#     > docker compose --profile all-64 up -d
#   For setup zabbix-6.4 (only servers)
#     > docker compose up -d
#
# For update to latest image:
#   > docker compose [--profile <prof_type>] [--profile <prof_type>] pull
#   > docker compose [--profile <prof_type>] [--profile <prof_type>] up -d
#  Or
#   > COMPOSE_PROFILES=<prof_type>[,<prof_type>] docker compose pull
#   > COMPOSE_PROFILES=<prof_type>[,<prof_type>] docker compose up -d
#-------------------------------------------------------------------
# Belov V.E.
# 2024-01-26

version: '3.8'
name: zabbix-6-4

services:

  mysql-server:
    # image: 8.0-oracle
    image: mysql:8.1
    profiles: ['', "all-64", "mysql-64"]
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    networks:
      zbx_net:
        aliases:
          - mysql-server
    # ports:
    #   - 3306:3306
    environment:
      - MYSQL_DATABASE=zabbix
      # В проде делать через secrets
      # - MYSQL_USER_FILE=/run/secrets/MYSQL_USER
      # - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/MYSQL_ROOT_PASSWORD
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
    # secrets:
    #   - MYSQL_USER
    #   - MYSQL_PASSWORD
    #   - MYSQL_ROOT_PASSWORD
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mysql_data:/var/lib/mysql:rw
      # - ./var/lib/mysql:/var/lib/mysql:rw
    stop_grace_period: 1m
    restart: unless-stopped   # always
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
      # Use TLS encryption for connections to database
      # - --require-secure-transport
      # - --ssl-ca=/run/secrets/root-ca.pem
      # - --ssl-cert=/run/secrets/server-cert.pem
      # - --ssl-key=/run/secrets/server-key.pem
    labels:
      description: "Zabbix MySQL server"


  zabbix-server-mysql:
    image: zabbix/zabbix-server-mysql:alpine-6.4-latest
    profiles: ['', "all-64", "mysql-64"]
    init: true
    networks:
      zbx_net:
        aliases:
          - zabbix-server
    ports:
      - 10051:10051
    # env_file:   # as an example
    # - ${ENV_VARS_DIRECTORY}/.env_srv_mysql
    environment:
      #- DB_SERVER_HOST=zabbix-64-mysql-server  # сделал через алиас
      - DB_SERVER_HOST=mysql-server
      - DB_SERVER_PORT=3306
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
      - ZBX_JAVAGATEWAY_ENABLE=true
      - ZBX_STARTJAVAPOLLERS=5
      - ZBX_ENABLE_SNMP_TRAPS=true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - snmptraps:/var/lib/zabbix/snmptraps:ro
      - ./var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
      - ./usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
      - ./usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
      - ./var/lib/zabbix/export:/var/lib/zabbix/export:rw
      - ./var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      # - ./var/lib/zabbix/dbscripts:/var/lib/zabbix/dbscripts:ro
      # - ./var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      # - ./var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
    tmpfs: /tmp
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    deploy:
      resources:
        limits:
          cpus: '0.70'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    stop_grace_period: 30s
    sysctls:
      - net.ipv4.ip_local_port_range=1024 64999
      - net.ipv4.conf.all.accept_redirects=0
      - net.ipv4.conf.all.secure_redirects=0
      - net.ipv4.conf.all.send_redirects=0
    restart: unless-stopped   # always
    depends_on:
      - mysql-server
    labels:
      description: "Zabbix server (MySQL)"


  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql:alpine-6.4-latest
    profiles: ['', "all-64", "mysql-64"]
    networks:
      zbx_net:
        aliases:
          - zabbix-web-nginx-mysql
    ports:
      - 8088:8080
    environment:
      - ZBX_SERVER_HOST=zabbix-server
      - DB_SERVER_HOST=mysql-server
        # - DB_SERVER_HOST=zabbix-64-mysql-server # сделал через алиас
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
      - PHP_TZ=Europe/Moscow
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./usr/share/zabbix/modules/:/usr/share/zabbix/modules/:ro
    restart: unless-stopped   # always
    depends_on:
      - mysql-server
      - zabbix-server-mysql
    labels:
      description: "Web-nginx for Zabbix MySQL"


  # For Host zabbix-server in config interface set:
  #   DNS name: zabbix-agen
  #   Connect to: DNS
  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-6.4-latest
    profiles: ["all-64", "agent-64"]
    networks:
      zbx_net:
        aliases:
          - zabbix-agent
          - zabbix-agent-passive
    # ports:
    #   - "10050:10050"
    environment:
      - ZBX_SERVER_HOST=zabbix-server # the IP/Dns of Zabbix server
      - ZBX_HOSTNAME=zabbix-agent
      - ZBX_ACTIVE_ALLOW=false
        # - ZBX_SOURCEIP=
        # - ZBX_DEBUGLEVEL=3
        # - ZBX_LOGREMOTECOMMANDS=0
        # - ZBX_FORCEACTIVECHECKSONSTART=0
        # - ZBX_HEARTBEAT_FREQUENCY=60
        # - ZBX_HOSTINTERFACE=
        # - ZBX_HOSTINTERFACEITEM=
        # - ZBX_PASSIVE_ALLOW=true
        # - ZBX_PASSIVESERVERS=
        # - ZBX_ACTIVE_ALLOW=true
        # - ZBX_ACTIVESERVERS=
        # - ZBX_LISTENIP=
        # - ZBX_LISTENBACKLOG=
        # - ZBX_STARTAGENTS=3
        # - ZBX_HOSTNAMEITEM=system.hostname
        # - ZBX_METADATA=
        # - ZBX_METADATAITEM=
        # - ZBX_REFRESHACTIVECHECKS=120
        # - ZBX_BUFFERSEND=5
        # - ZBX_BUFFERSIZE=100
        # - ZBX_MAXLINESPERSECOND=20
        # - ZBX_ALIAS=""
        # - ZBX_TIMEOUT=3
        # - ZBX_UNSAFEUSERPARAMETERS=0
        # - ZBX_LOADMODULE="dummy1.so,dummy2.so,dummy10.so"
        # - ZBX_TLSCONNECT=unencrypted
        # - ZBX_TLSACCEPT=unencrypted
        # - ZBX_TLSCAFILE=
        # - ZBX_TLSCRLFILE=
        # - ZBX_TLSSERVERCERTISSUER=
        # - ZBX_TLSSERVERCERTSUBJECT=
        # - ZBX_TLSCERTFILE=
        # - ZBX_TLSKEYFILE=
        # - ZBX_TLSPSKIDENTITY=
        # - ZBX_TLSPSKFILE=
        # - ZBX_DENYKEY=system.run[*]
        # - ZBX_ALLOWKEY=
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - agent:/etc/zabbix/
      # вместо предыдущего
      # - ./agent/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
      # - ./agent/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      # - ./agent/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      # - ./agent/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
    tmpfs: /tmp
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M
      mode: global
    init: true
    privileged: true                # access mode for allowing resource access
    pid: "host"
    restart: unless-stopped   # always
    depends_on:
      - zabbix-server-mysql
    stop_grace_period: 5s
    labels:
      description: "Zabbix agent"


  zabbix-snmptraps:
  # Override snmptrapd command arguments to receive SNMP traps by DNS
  # It must be done with ZBX_SNMP_TRAP_USE_DNS=true environment variable
  #  command: /usr/sbin/snmptrapd -C -c /etc/snmp/snmptrapd.conf -Lo -A
    image: zabbix/zabbix-snmptraps:alpine-6.4-latest
    profiles:  ["all-64", "agent-64"]
    networks:
      zbx_net:
        aliases:
          - zabbix-snmptraps
    ports:
      - 162:1162/udp
    volumes:
    - snmptraps:/var/lib/zabbix/snmptraps:rw
    environment:
      - ZBX_SNMP_TRAP_DATE_FORMAT=+%Y%m%d.%H%M%S
      - ZBX_SNMP_TRAP_FORMAT=\n
        # To use DNS instead of sender IP override container's command: /usr/sbin/snmptrapd -C -c /etc/snmp/snmptrapd.conf -Lo -A
        # Need to remove "-n" command argument
      - ZBX_SNMP_TRAP_USE_DNS=false
    tmpfs: /tmp
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    restart: unless-stopped   # always
    stop_grace_period: 5s
    labels:
      description: "Zabbix snmptraps"


  # adminer:
  #   image: adminer
  #   profiles:
  #     - debug
  #   networks:
  #     - zbx_net
  #   ports:
  #     - 8086:8080
  #   restart: unless-stopped
  #   depends_on:
  #     - mysql-server


networks:
  zbx_net:
    driver: bridge


volumes:
  mysql_data:
  snmptraps:
  agent:


# secrets:
#   MYSQL_USER:
#     file: ./.MYSQL_USER
#   MYSQL_PASSWORD:
#     file: ./.MYSQL_PASSWORD
#   MYSQL_ROOT_USER:
#     file: ./.MYSQL_ROOT_USER
#   MYSQL_ROOT_PASSWORD:
#     file: ./.MYSQL_ROOT_PASSWORD