# For setup:
# docker-compose.yml for Zabbix 7.0 6.4 MySQL/PostgreSQL, Nginx, Agent, Trapper
# For setup:
# docker compose [--profile <prof_type>] [--profile <prof_type>] up -d
# or
# COMPOSE_PROFILES=<prof_type>[,<prof_type>] docker compose up
# where <prof_type>:
#   Complect:
#     all-7 -> Select zabbix-server DB type mysql. zabbix-proxy DB mysql3. All version 7.0
#     all-64 -> Select zabbix-server DB type mysql. zabbix-proxy DB mysql3. All version 6.4
#   Agent:
#     agent-7  -> Select agent and trapper version 7.0
#     agent-64 -> Select agent and trapper version 6.4
#    DB:
#     mysql-7 | pgsql-7 -> zabbix server, nginx DB for zabbix-7.0
#     mysql-64 | pgsql-64 -> zabbix server, nginx DB for zabbix-6.4
#    Proxy:
#     proxy-sqlite-7 | proxy-mysql-7 -> Select zabbix proxy server DB for zabbix-7
#     proxy-sqlite-64 | proxy-mysql-64 -> Select zabbix proxy server DB for zabbix-6.4
#
# If you do not specify a profile, they will be installed:
#   > mysql-server, zabbix-server-mysql, zabbix-web-nginx-mysql for zabbix-6.4
#
# Example:
# For full setup zabbix-mysql 6.4:
#    > docker compose --profile all-64 up -d
#
# For full setup zabbix-pgsql 7.0:
#     > docker compose --profile pgsql-7 --profile agent-7 --profile proxy-sqlite-7 up -d
#   or
#     > COMPOSE_PROFILES=pgsql-7,agent-7,proxy-sqlite-7 docker compose up
#
# For setup zabbix-7.0 (only servers)
#     > docker compose up -d
#
# For update image to latest version:
#   > docker compose [--profile <prof_type>] [--profile <prof_type>] pull
#   > docker compose [--profile <prof_type>] [--profile <prof_type>] up -d
# or
#   > COMPOSE_PROFILES=<prof_type>[,<prof_type>] docker compose pull
#   > COMPOSE_PROFILES=<prof_type>[,<prof_type>] docker compose up -d
#
# Example:
#   > docker compose --profile agent-7 pull -d
#   > docker compose --profile agent-7 up -d
#-------------------------------------------------------------------
# Belov V.E.
# 2025-01-26


name: zabbix
services:

#----------- DB Server -----------
  mysql-server-6.4:
    # image: 8.0-oracle
    image: mysql:8.1
    profiles: ["all-64", "mysql-64"]
    restart: unless-stopped   # always
    networks:
      zbx_net:
        aliases:
          - mysql-server
    # ports:
    #   - 3306:3306
    env_file:
      - ./env_db_mysql
    # secrets:
    #   - MYSQL_USER
    #   - MYSQL_PASSWORD
    #   - MYSQL_ROOT_PASSWORD
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mysql_data:/var/lib/mysql:rw
      # - ./var/lib/mysql:/var/lib/mysql:rw
    stop_grace_period: 1m
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
      # Use TLS encryption for connections to database
      # - --require-secure-transport
      # - --ssl-ca=/run/secrets/root-ca.pem
      # - --ssl-cert=/run/secrets/server-cert.pem
      # - --ssl-key=/run/secrets/server-key.pem
    labels:
      description: "Zabbix MySQL server"

  mysql-server-7.0:
    image: mysql:8.0-oracle
    profiles: ['', "all-7", "mysql-7"]
    restart: unless-stopped   # always
    networks:
      zbx_net:
        aliases:
          - mysql-server
    # ports:
    #   - 3306:3306
    env_file:
      - ./env_db_mysql
    # secrets:
    #   - MYSQL_USER
    #   - MYSQL_PASSWORD
    #   - MYSQL_ROOT_PASSWORD
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mysql_data:/var/lib/mysql:rw
      # - ./var/lib/mysql:/var/lib/mysql:rw
    stop_grace_period: 1m
    command:
      - mysqld
      - --skip-mysqlx
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
      # Use TLS encryption for connections to database
      # - --require-secure-transport
      # - --ssl-ca=/run/secrets/root-ca.pem
      # - --ssl-cert=/run/secrets/server-cert.pem
      # - --ssl-key=/run/secrets/server-key.pem
    labels:
      description: "Zabbix MySQL server"


  postgres-server-6.4:
    image: postgres:15-alpine
    profiles: ["pgsql-64"]
    restart: unless-stopped   # always
    networks:
      zbx_net:
        aliases:
          - postgres-server
    # ports:
    #   - 5432:5432
    env_file:
      - ./env_db_pgsql
    # secrets:
    #   - POSTGRES_USER
    #   - POSTGRES_PASSWORD
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # - ./var/lib/postgresql/data:/var/lib/postgresql/data:rw
      - pgsql_data:/var/lib/postgresql/data:rw
      # - ./.ZBX_DB_CA_FILE:/run/secrets/root-ca.pem:ro
      # - ./.ZBX_DB_CERT_FILE:/run/secrets/server-cert.pem:ro
      # - ./.ZBX_DB_KEY_FILE:/run/secrets/server-key.pem:ro
    # command: -c ssl=on -c ssl_cert_file=/run/secrets/server-cert.pem -c ssl_key_file=/run/secrets/server-key.pem -c ssl_ca_file=/run/secrets/root-ca.pem
    stop_grace_period: 1m
    labels:
      description: "Zabbix PostgreSQL server"


  postgres-server-7.0:
    image: postgres:16-alpine
    profiles: ["pgsql-7"]
    restart: unless-stopped   # always
    networks:
      zbx_net:
        aliases:
          - postgres-server
    # ports:
    #   - 5432:5432
    env_file:
      - ./env_db_pgsql
    # secrets:
    #   - POSTGRES_USER
    #   - POSTGRES_PASSWORD
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # - ./var/lib/postgresql/data:/var/lib/postgresql/data:rw
      - pgsql_data:/var/lib/postgresql/data:rw
      # - ./.ZBX_DB_CA_FILE:/run/secrets/root-ca.pem:ro
      # - ./.ZBX_DB_CERT_FILE:/run/secrets/server-cert.pem:ro
      # - ./.ZBX_DB_KEY_FILE:/run/secrets/server-key.pem:ro
    # command: -c ssl=on -c ssl_cert_file=/run/secrets/server-cert.pem -c ssl_key_file=/run/secrets/server-key.pem -c ssl_ca_file=/run/secrets/root-ca.pem
    stop_grace_period: 1m
    labels:
      description: "Zabbix PostgreSQL server"
#-------------------------------------


#----------- Zabbix Server -----------
  zabbix-server-mysql-6.4:
    image: zabbix/zabbix-server-mysql:alpine-6.4-latest
    profiles: ["all-64", "mysql-64"]
    extends:
      file: compose-common.yaml
      service: zabbix-server
    ports:
      - 10051:10051
    volumes:
      - /etc/timezone:/etc/timezone:ro
    env_file:
      - ./env_db_mysql
    depends_on:
      - mysql-server-6.4
    labels:
      description: "Zabbix server (MySQL)"


  zabbix-server-mysql-7.0:
    image: zabbix/zabbix-server-mysql:alpine-7.0-latest
    profiles: ['', "all-7", "mysql-7"]
    extends:
      file: compose-common.yaml
      service: zabbix-server
    ports:
      - 10051:10051
    volumes:
      - /etc/timezone:/etc/timezone:ro
    env_file:
      - ./env_db_mysql
    depends_on:
      - mysql-server-7.0
    labels:
      description: "Zabbix server (MySQL)"


  zabbix-server-pgsql-6.4:
    image: zabbix/zabbix-server-pgsql:alpine-6.4-latest
    profiles: ["pgsql-64"]
    extends:
      file: compose-common.yaml
      service: zabbix-server
    volumes:
      - /etc/timezone:/etc/timezone:ro
      # - ./.ZBX_DB_CA_FILE:/run/secrets/root-ca.pem:ro
      # - ./.ZBX_DB_CERT_FILE:/run/secrets/server-cert.pem:ro
      # - ./.ZBX_DB_KEY_FILE:/run/secrets/server-key.pem:ro
    env_file:
      - ./env_db_pgsql
    # secrets:
    #   - POSTGRES_USER
    #   - POSTGRES_PASSWORD
    depends_on:
      - postgres-server-6.4
    labels:
        description: "Zabbix server (PostgreSQL)"


  zabbix-server-pgsql-7.0:
    image: zabbix/zabbix-server-pgsql:alpine-7.0-latest
    profiles: ["pgsql-7"]
    extends:
      file: compose-common.yaml
      service: zabbix-server
    environment:
      - ZBX_HOSTNAME=zabbix-server
    volumes:
      - /etc/timezone:/etc/timezone:ro
      # - ./.ZBX_DB_CA_FILE:/run/secrets/root-ca.pem:ro
      # - ./.ZBX_DB_CERT_FILE:/run/secrets/server-cert.pem:ro
      # - ./.ZBX_DB_KEY_FILE:/run/secrets/server-key.pem:ro
    env_file:
      - ./env_db_pgsql
    # secrets:
    #   - POSTGRES_USER
    #   - POSTGRES_PASSWORD
    depends_on:
      - postgres-server-7.0
    labels:
        description: "Zabbix server (PostgreSQL)"
#-------------------------------------


#----------- Nginx Server -----------
  zabbix-web-nginx-mysql-6.4:
    image: zabbix/zabbix-web-nginx-mysql:alpine-6.4-latest
    profiles: ["all-64", "mysql-64"]
    extends:
      file: compose-common.yaml
      service: zabbix-web-nginx
    env_file:
      - ./env_db_mysql
    environment:
      - PHP_TZ=Europe/Moscow
    depends_on:
      - mysql-server-6.4
      - zabbix-server-mysql-6.4
    labels:
      description: "Web-nginx for Zabbix MySQL"


  zabbix-web-nginx-mysql-7.0:
    image: zabbix/zabbix-web-nginx-mysql:alpine-7.0-latest
    profiles: ['', "all-7", "mysql-7"]
    extends:
      file: compose-common.yaml
      service: zabbix-web-nginx
    env_file:
      - ./env_db_mysql
    environment:
      - PHP_TZ=Europe/Moscow
    depends_on:
      - mysql-server-7.0
      - zabbix-server-mysql-7.0
    labels:
      description: "Web-nginx for Zabbix MySQL"


  zabbix-web-nginx-pgsql-6.4:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-6.4-latest
    profiles: ["pgsql-64"]
    extends:
      file: compose-common.yaml
      service: zabbix-web-nginx
    env_file:
      - ./env_db_pgsql
    environment:
      - PHP_TZ=Europe/Moscow
    # volumes:
    #   - ./env_vars/.ZBX_DB_CA_FILE:/run/secrets/root-ca.pem:ro
    #   - ./env_vars/.ZBX_DB_CERT_FILE:/run/secrets/server-cert.pem:ro
    #   - ./env_vars/.ZBX_DB_KEY_FILE:/run/secrets/server-key.pem:ro
    # secrets:
    #   - POSTGRES_USER
    #   - POSTGRES_PASSWORD
    depends_on:
      - postgres-server-6.4
      - zabbix-server-pgsql-6.4
    labels:
      description: "Web-nginx for Zabbix PostgreSQL"


  zabbix-web-nginx-pgsql-7.0:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-7.0-latest
    profiles: ["pgsql-7"]
    extends:
      file: compose-common.yaml
      service: zabbix-web-nginx
    env_file:
      - ./env_db_pgsql
    environment:
      - PHP_TZ=Europe/Moscow
    # volumes:
    #   - ./env_vars/.ZBX_DB_CA_FILE:/run/secrets/root-ca.pem:ro
    #   - ./env_vars/.ZBX_DB_CERT_FILE:/run/secrets/server-cert.pem:ro
    #   - ./env_vars/.ZBX_DB_KEY_FILE:/run/secrets/server-key.pem:ro
    # secrets:
    #   - POSTGRES_USER
    #   - POSTGRES_PASSWORD
    depends_on:
      - postgres-server-7.0
      - zabbix-server-pgsql-7.0
    labels:
      description: "Web-nginx for Zabbix PostgreSQL"
#-------------------------------------


#----------- zabbix-agent ------------
  zabbix-agent-6.4:
    image: zabbix/zabbix-agent:alpine-6.4-latest
    profiles: ["all-64", "agent-64"]
    extends:
      file: compose-common.yaml
      service: zabbix-agent
    # ports:
    #   - "10050:10050"
    environment:
      - ZBX_HOSTNAME=zabbix-server
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - agent:/etc/zabbix/
      # вместо предыдущего
      # - ./agent/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
      # - ./agent/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      # - ./agent/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      # - ./agent/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
    labels:
      description: "Zabbix agent"


  zabbix-agent-7.0:
    image: zabbix/zabbix-agent:alpine-7.0-latest
    profiles: ["all-7", "agent-7"]
    extends:
      file: compose-common.yaml
      service: zabbix-agent
    # ports:
    #   - "10050:10050"
    environment:
      - ZBX_HOSTNAME=zabbix-server
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - agent:/etc/zabbix/
      # вместо предыдущего
      # - ./agent/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
      # - ./agent/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      # - ./agent/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      # - ./agent/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
    labels:
      description: "Zabbix agent"


  zabbix-snmptraps-6.4:
  # Override snmptrapd command arguments to receive SNMP traps by DNS
  # It must be done with ZBX_SNMP_TRAP_USE_DNS=true environment variable
  #  command: /usr/sbin/snmptrapd -C -c /etc/snmp/snmptrapd.conf -Lo -A
    image: zabbix/zabbix-snmptraps:alpine-6.4-latest
    profiles: ["all-64", "agent-64"]
    extends:
      file: compose-common.yaml
      service: zabbix-snmptraps
    volumes:
      - snmptraps:/var/lib/zabbix/snmptraps:rw
    labels:
      description: "Zabbix snmptraps"


  zabbix-snmptraps-7.0:
  # Override snmptrapd command arguments to receive SNMP traps by DNS
  # It must be done with ZBX_SNMP_TRAP_USE_DNS=true environment variable
  #  command: /usr/sbin/snmptrapd -C -c /etc/snmp/snmptrapd.conf -Lo -A
    image: zabbix/zabbix-snmptraps:alpine-7.0-latest
    profiles: ["all-7", "agent-7"]
    extends:
      file: compose-common.yaml
      service: zabbix-snmptraps
    volumes:
      - snmptraps:/var/lib/zabbix/snmptraps:rw
      - snmptrapd_config:/var/lib/zabbix/snmptrapd_config:rw
    labels:
      description: "Zabbix snmptraps"


#----------- Proxy Server -----------
  zabbix-proxy-sqlite3-6.4:
    image: zabbix/zabbix-proxy-sqlite3:alpine-6.4-latest
    profiles: ["all-64", "proxy-sqlite-64"]
    extends:
      file: compose-common.yaml
      service: zabbix-proxy
    restart: unless-stopped   # always
    ports:
      - 10061:10051
    labels:
      description: "Zabbix proxy with SQLite3 database support"

  zabbix-proxy-mysql-6.4:
    image: zabbix/zabbix-proxy-mysql:alpine-6.4-latest
    profiles: ["proxy-mysql-64"]
    extends:
      file: compose-common.yaml
      service: zabbix-proxy
    ports:
      - 10061:10051
    env_file:
      - ./env_db_mysql_proxy
    # secrets:
    #   - MYSQL_USER
    #   - MYSQL_PASSWORD
      # - client-key.pem
      # - client-cert.pem
      # - root-ca.pem
    labels:
      description: "Zabbix proxy with MySQL database support"

  zabbix-proxy-sqlite3-7.0:
    image: zabbix/zabbix-proxy-sqlite3:alpine-7.0-latest
    profiles: ['all-7', "proxy-sqlite-7"]
    extends:
      file: compose-common.yaml
      service: zabbix-proxy
    restart: unless-stopped   # always
    ports:
      - 10061:10051
    labels:
      description: "Zabbix proxy with SQLite3 database support"

  zabbix-proxy-mysql-7.0:
    image: zabbix/zabbix-proxy-mysql:alpine-7.0-latest
    profiles: ["proxy-mysql-7"]
    extends:
      file: compose-common.yaml
      service: zabbix-proxy
    ports:
      - 10061:10051
    env_file:
      - ./env_db_mysql_proxy
    # secrets:
    #   - MYSQL_USER
    #   - MYSQL_PASSWORD
      # - client-key.pem
      # - client-cert.pem
      # - root-ca.pem
    labels:
      description: "Zabbix proxy with MySQL database support"
#-------------------------------------


  # adminer:
  #   image: adminer
  #   restart: unless-stopped
  #   profiles:
  #     - debug
  #   networks:
  #     - zbx_net
  #   ports:
  #     - 8086:8080
  #   depends_on:
  #     - mysql-server-?


networks:
  ## Config: Stack internal network
  zbx_net:
    driver: bridge
  ## Config: External shared network with other containers
  # zbx_net:
  #   # external: true    # don't create network
  #   name: zabbix_network


volumes:
  mysql_data:
  pgsql_data:
  snmptraps:
  snmptrapd_config:
  agent:


# secrets:
#   MYSQL_USER:
#     file: ./.MYSQL_USER
#   MYSQL_PASSWORD:
#     file: ./.MYSQL_PASSWORD
#   MYSQL_ROOT_USER:
#     file: ./.MYSQL_ROOT_USER
#   MYSQL_ROOT_PASSWORD:
#     file: ./.MYSQL_ROOT_PASSWORD
#   POSTGRES_USER:
#     file: ./.POSTGRES_USER
#   POSTGRES_PASSWORD:
#     file: ./.POSTGRES_PASSWORD
