# Zabbix 6.0.20 + MySQL 8.0 + Agent
# Belov V
# 2023-08-03
version: '3.1'
name: zabbix-6-0

services:

  db:
    image: mysql:8.0
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    container_name: zabbix-60-db
    networks:
      - zbx_net
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped   # always
    command:
      # - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin


  server:
    image: zabbix/zabbix-server-mysql:alpine-6.0-latest
    container_name: zabbix-60
    networks:
      - zbx_net
    # ports:
    #   - 10051:10051
    environment:
      - DB_SERVER_HOST=zabbix-60-db
      - DB_SERVER_PORT=3306
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - export:/var/lib/zabbix/export
      - snmptraps:/var/lib/zabbix/snmptraps
    restart: unless-stopped   # always
    depends_on:
      - db


  web:
    image: zabbix/zabbix-web-nginx-mysql:alpine-6.0-latest
    container_name: zabbix-60-web
    networks:
      - zbx_net
    ports:
      - 8088:8080
    environment:
      - ZBX_SERVER_HOST=zabbix-60
      - DB_SERVER_HOST=zabbix-60-db
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
      - PHP_TZ=Europe/Moscow
    restart: unless-stopped   # always
    depends_on:
      - db
      - server


  agent:
    image: zabbix/zabbix-agent:alpine-6.0-latest
    container_name: zabbix-60-agent # В настройке хоста Zabbix server изменить интрефейс сервена на dns zabbix-60-agent
    privileged: true                # access mode for allowing resource access
    networks:
      - zbx_net
    environment:
      - ZBX_SERVER_HOST=zabbix-60  # the IP/Dns of Zabbix server
      - ZBX_HOSTNAME=zabbix-60
      - ZBX_ACTIVE_ALLOW=false
    volumes:
      - agent:/etc/zabbix/
    restart: unless-stopped   # always
    depends_on:
      - server

  # adminer:
  #   image: adminer
  #   networks:
  #     - zbx_net
  #   ports:
  #     - 8086:8080
  #   restart: always
  #   depends_on:
  #     - db

networks:
  zbx_net:

volumes:
  mysql_data:
  export:
  snmptraps:
  agent:
